mysql_root_password: devopsmaonamassa
mysql_databases:
  - name: notes
    encoding: UTF-8
    collation: utf-8_general_ci
mysql_users:
  - name: notesapp
    host: "%"
    password: devopsmaonamassa
    priv: "notes.*:ALL"